/**
 * Dados simulados para o Modo de Teste Local
 * Fundação CDL-BH
 */

export const PROJETOS_INICIAIS = [
  { id: 1, nome: 'Projeto Afeto', descricao: 'Acolhimento e suporte socioemocional a famílias vulneráveis de BH.' },
  { id: 2, nome: 'Afeto Empreendedorismo', descricao: 'Capacitação empreendedora e fomento à geração de renda comunitária.' },
  { id: 3, nome: 'Alimentando Vidas', descricao: 'Segurança alimentar, arrecadação e doação de cestas básicas e alimentos.' },
  { id: 4, nome: 'Brincadeira é Coisa Séria', descricao: 'Oficinas socioeducativas e recreativas para infância e juventude.' },
  { id: 5, nome: 'Brinquedoteca Itinerante', descricao: 'Espaço móvel de ludicidade e leitura em escolas e vilas da capital.' },
  { id: 6, nome: 'Despertar Empreendedor', descricao: 'Formação para jovens no mundo dos negócios e comércio local.' },
  { id: 7, nome: 'Liderança Jovem', descricao: 'Desenvolvimento de habilidades de liderança e cidadania para adolescentes.' },
  { id: 8, nome: 'Natal de Todo Mundo', descricao: 'Campanha de fim de ano com arrecadação de brinquedos e alimentos natalinos.' },
  { id: 9, nome: 'Programa Educação e Trabalho (PET)', descricao: 'Inclusão produtiva de jovens aprendizes no mercado de trabalho mineiro.' },
  { id: 10, nome: 'Protagonizar em Cena', descricao: 'Incentivo cultural e oficinas teatrais comunitárias.' },
  { id: 11, nome: 'Sorridente', descricao: 'Assistência à saúde bucal e atendimento odontológico preventivo.' },
  { id: 12, nome: 'Ver é Bom Demais', descricao: 'Triagem oftalmológica e doação de óculos de grau para estudantes.' },
  { id: 13, nome: 'Outro', descricao: 'Demandas e iniciativas especiais da Fundação CDL-BH.' },
];

export const PROJETOS_PADRAO = PROJETOS_INICIAIS.map(p => p.nome);

export const FORNECEDORES_INICIAIS = [
  {
    id: 1,
    nome: 'Maria Silva',
    empresa_pf: 'Distribuidora Silva LTDA',
    tipo_pessoa: 'PJ',
    favorito: true,
    cnpj: '12.345.678/0001-90',
    email: 'maria@silva.com',
    telefone: '(31) 99999-1111',
    palavra_chave: 'fraldas, higiene, doações',
    projeto: 'Projeto Afeto',
    observacao: 'Fornecedora parceira desde 2022. Sempre entrega pontualmente.',
    permissao_para: ['Fornecer materiais', 'Doação de produtos'],
    status: 'ativo',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    nome: 'João Costa',
    empresa_pf: 'JC Transportes & Cargas ME',
    tipo_pessoa: 'PJ',
    favorito: false,
    cnpj: '98.765.432/0001-10',
    email: 'joao@jctransportes.com',
    telefone: '(31) 98888-2222',
    palavra_chave: 'transporte, logística, van, frete',
    projeto: 'Sorridente',
    observacao: 'Disponibiliza van adaptada para ações sociais da fundação.',
    permissao_para: ['Transporte e logística'],
    status: 'ativo',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    nome: 'Ana Pereira',
    empresa_pf: 'Papelaria & Bazar Pereira',
    tipo_pessoa: 'PJ',
    favorito: true,
    cnpj: '11.222.333/0001-44',
    email: 'ana@papelaria.com',
    telefone: '(31) 97777-3333',
    palavra_chave: 'material escolar, cadernos, lápis, mochilas',
    projeto: 'Programa Educação e Trabalho (PET)',
    observacao: 'Concede desconto especial de 15% para a fundação.',
    permissao_para: ['Fornecer materiais', 'Doação de produtos'],
    status: 'ativo',
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    nome: 'Carlos Eduardo Santos',
    empresa_pf: 'InfoTech Soluções Digitais',
    tipo_pessoa: 'PJ',
    favorito: false,
    cnpj: '22.333.444/0001-55',
    email: 'carlos@infotech.com.br',
    telefone: '(31) 96666-4444',
    palavra_chave: 'computadores, manutenção, informática, redes',
    projeto: 'Afeto Empreendedorismo',
    observacao: 'Responsável pela manutenção dos laboratórios de informática.',
    permissao_para: ['Prestar serviço', 'Consultoria'],
    status: 'ativo',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    nome: 'Dr. Fernando Albuquerque',
    empresa_pf: 'Pessoa Física',
    tipo_pessoa: 'PF',
    favorito: true,
    cnpj: '333.444.555-66',
    email: 'fernando.albuquerque@email.com',
    telefone: '(31) 95555-4321',
    palavra_chave: 'odontologia, consultas, saúde bucal',
    projeto: 'Sorridente',
    observacao: 'Dentista voluntário que realiza atendimentos clínicos semanais.',
    permissao_para: ['Prestar serviço', 'Consultoria'],
    status: 'ativo',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 6,
    nome: 'Roberto Magalhães',
    empresa_pf: 'Supermercado Central de Alimentos',
    tipo_pessoa: 'PJ',
    favorito: false,
    cnpj: '33.444.555/0001-66',
    email: 'contato@supercentral.com.br',
    telefone: '(31) 95555-5555',
    palavra_chave: 'cestas básicas, alimentos, perecíveis',
    projeto: 'Alimentando Vidas',
    observacao: 'Contrato temporariamente pausado para renegociação anual.',
    permissao_para: ['Alimentação', 'Doação de produtos'],
    status: 'inativo',
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

// Gera datas dinâmicas para simular documentos vigentes, vencendo e vencidos
const now = new Date();
const dateInDays = (dias) => {
  const d = new Date(now);
  d.setDate(d.getDate() + dias);
  return d.toISOString().split('T')[0];
};

export const DOCUMENTOS_INICIAIS = [
  {
    id: 1,
    fornecedor_id: 1,
    nome: 'Contrato Anual de Fornecimento de Higiene',
    tipo: 'Contrato',
    data_vencimento: dateInDays(14), // Vence em 14 dias (aparece no alerta do dashboard!)
    arquivo_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    observacao: 'Renovação obrigatória para continuar os atendimentos às famílias.',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    fornecedor_id: 1,
    nome: 'Certidão Negativa de Débitos Federais (CND)',
    tipo: 'Certidão',
    data_vencimento: dateInDays(120), // Vigente por 4 meses
    arquivo_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    observacao: 'Emitida pela Receita Federal, tudo regular.',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    fornecedor_id: 2,
    nome: 'Alvará Municipal de Transporte de Passageiros',
    tipo: 'Alvará',
    data_vencimento: dateInDays(-5), // Vencido há 5 dias (alerta crítico!)
    arquivo_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    observacao: 'Notificar fornecedor para envio do comprovante de renovação.',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    fornecedor_id: 3,
    nome: 'Nota Fiscal Eletrônica #008412',
    tipo: 'Nota Fiscal',
    data_vencimento: null,
    arquivo_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    observacao: 'Ref. kits escolares distribuídos aos alunos do PET.',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const BENEFICIARIOS_INICIAIS = [
  {
    id: 1,
    nome: 'Lucas Gabriel dos Santos',
    cpf: '123.456.789-01',
    favorito: true,
    data_nascimento: '2007-04-15',
    telefone: '(31) 98765-4321',
    email: 'lucas.santos@email.com',
    projeto_social: 'Programa Educação e Trabalho (PET)',
    projeto: 'Programa Educação e Trabalho (PET)',
    bairro: 'Vila Esperança - BH',
    status: 'Ativo',
    observacao: 'Jovem aprendiz matriculado no curso profissionalizante de logística.',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    nome: 'Camila Fernandes Costa',
    cpf: '987.654.321-99',
    favorito: false,
    data_nascimento: '2010-09-22',
    telefone: '(31) 99123-4567',
    email: 'familia.fernandes@email.com',
    projeto_social: 'Ver é Bom Demais',
    projeto: 'Ver é Bom Demais',
    bairro: 'Barreiro - BH',
    status: 'Ativo',
    observacao: 'Triagem oftalmológica concluída. Aguardando entrega de óculos corretivos.',
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    nome: 'Dona Maria Aparecida de Jesus',
    cpf: '555.666.777-88',
    favorito: true,
    data_nascimento: '1965-02-10',
    telefone: '(31) 98222-3344',
    email: '',
    projeto_social: 'Alimentando Vidas',
    projeto: 'Alimentando Vidas',
    bairro: 'Aglomerado da Serra - BH',
    status: 'Ativo',
    observacao: 'Família com 4 dependentes atendida com cesta básica mensal.',
    created_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const PRESTADORES_INICIAIS = [
  {
    id: 1,
    nome: 'Dra. Luciana Rezende',
    empresa_pf: 'Rezende & Associados Advocacia',
    tipo_pessoa: 'PJ',
    documento: '14.285.901/0001-44',
    cnpj: '14.285.901/0001-44',
    servico: 'Assessoria Jurídica e Estatutária',
    especialidade: 'Direito do Terceiro Setor',
    telefone: '(31) 98765-1234',
    email: 'luciana@rezendeadv.com.br',
    projeto: 'Projeto Afeto',
    status: 'Ativo',
    favorito: true,
    cidade: 'Belo Horizonte',
    observacoes: 'Prestadora responsável pela conformidade jurídica e estatutos da Fundação.',
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    nome: 'Marcos Vinicius Moreira',
    empresa_pf: 'Moreira Consultoria Contábil',
    tipo_pessoa: 'PJ',
    documento: '22.341.879/0001-55',
    cnpj: '22.341.879/0001-55',
    servico: 'Contabilidade e Auditoria Fiscal',
    especialidade: 'Auditoria e Balanços do Terceiro Setor',
    telefone: '(31) 99123-8899',
    email: 'marcos@moreiracontabil.com.br',
    projeto: 'Alimentando Vidas',
    status: 'Ativo',
    favorito: false,
    cidade: 'Belo Horizonte',
    observacoes: 'Acompanhamento mensal das prestações de contas de projetos incentivados.',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    nome: 'Rodrigo Soares Almeida',
    empresa_pf: 'Rodrigo Soares Almeida',
    tipo_pessoa: 'PF',
    documento: '333.444.555-66',
    cpf: '333.444.555-66',
    servico: 'Instrutor de Empreendedorismo & Vendas',
    especialidade: 'Capacitação Profissional de Jovens',
    telefone: '(31) 98455-7711',
    email: 'rodrigo.soares@consultor.com',
    projeto: 'Despertar Empreendedor',
    status: 'Ativo',
    favorito: true,
    cidade: 'Contagem',
    observacoes: 'Instrutor das oficinas práticas para turmas de adolescentes.',
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    nome: 'ClimaTech Climatização & Engenharia',
    empresa_pf: 'ClimaTech Serviços Prediais LTDA',
    tipo_pessoa: 'PJ',
    documento: '31.908.765/0001-12',
    cnpj: '31.908.765/0001-12',
    servico: 'Manutenção de Ar-Condicionado e Elétrica',
    especialidade: 'Infraestrutura Predial',
    telefone: '(31) 3211-4500',
    email: 'contato@climatechbh.com.br',
    projeto: 'Programa Educação e Trabalho (PET)',
    status: 'Ativo',
    favorito: false,
    cidade: 'Belo Horizonte',
    observacoes: 'Contrato de manutenção predial periódica nas salas de aula.',
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    nome: 'Dra. Patrícia Helena Silveira',
    empresa_pf: 'Dra. Patrícia Helena Silveira',
    tipo_pessoa: 'PF',
    documento: '777.888.999-00',
    cpf: '777.888.999-00',
    servico: 'Atendimento Odontológico Preventivo',
    especialidade: 'Odontopediatria Social',
    telefone: '(31) 99344-5566',
    email: 'dra.patricia@odontobh.org',
    projeto: 'Sorridente',
    status: 'Ativo',
    favorito: true,
    cidade: 'Belo Horizonte',
    observacoes: 'Dentista parceira responsável pelos mutirões de saúde bucal nas escolas.',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

export const PARCEIROS_INICIAIS = [
  {
    id: 1,
    nome: 'Banco Inter',
    empresa_pf: 'Banco Inter S.A.',
    tipo_pessoa: 'PJ',
    documento: '00.416.968/0001-01',
    cnpj: '00.416.968/0001-01',
    tipo_parceria: 'Empresa Mantenedora',
    responsavel: 'Camila Rocha',
    cargo_responsavel: 'Gerente Executiva de ESG & Comunidade',
    telefone: '(31) 3003-4070',
    email: 'esg@bancointer.com.br',
    projeto: 'Programa Educação e Trabalho (PET)',
    status: 'Ativo',
    favorito: true,
    contribuicao: 'Aporte financeiro anual e programas de mentoria para jovens.',
    created_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    nome: 'PUC Minas',
    empresa_pf: 'Sociedade Mineira de Cultura (PUC Minas)',
    tipo_pessoa: 'PJ',
    documento: '17.178.195/0001-67',
    cnpj: '17.178.195/0001-67',
    tipo_parceria: 'Instituição Educacional',
    responsavel: 'Prof. Dr. André Mendonça',
    cargo_responsavel: 'Diretor de Extensão Comunitária',
    telefone: '(31) 3319-4444',
    email: 'extensao@pucminas.br',
    projeto: 'Liderança Jovem',
    status: 'Ativo',
    favorito: true,
    contribuicao: 'Bolsas de estudo, uso de laboratórios de informática e extensão acadêmica.',
    created_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    nome: 'Instituto Unimed-BH',
    empresa_pf: 'Instituto Unimed-BH Cooperativa',
    tipo_pessoa: 'PJ',
    documento: '16.513.178/0001-23',
    cnpj: '16.513.178/0001-23',
    tipo_parceria: 'Patrocinador Social',
    responsavel: 'Beatriz Neves',
    cargo_responsavel: 'Coordenadora de Projetos de Saúde',
    telefone: '(31) 3229-6000',
    email: 'projetos@institutounimedbh.com.br',
    projeto: 'Sorridente',
    status: 'Ativo',
    favorito: true,
    contribuicao: 'Kits de higiene bucal, material educativo e custeio de profissionais.',
    created_at: new Date(Date.now() - 140 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 140 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    nome: 'Fundação Dom Cabral (FDC)',
    empresa_pf: 'Fundação Dom Cabral',
    tipo_pessoa: 'PJ',
    documento: '19.467.432/0001-55',
    cnpj: '19.467.432/0001-55',
    tipo_parceria: 'Apoio Institucional & Gestão',
    responsavel: 'Lucas Faria',
    cargo_responsavel: 'Líder de Iniciativas Sociais',
    telefone: '(31) 3589-7700',
    email: 'lucas.faria@fdc.org.br',
    projeto: 'Afeto Empreendedorismo',
    status: 'Ativo',
    favorito: false,
    contribuicao: 'Capacitação em governança, planejamento estratégico e mentoria de lideranças.',
    created_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    nome: 'Dra. Heloísa Drummond',
    empresa_pf: 'Dra. Heloísa Drummond',
    tipo_pessoa: 'PF',
    documento: '456.789.012-34',
    cpf: '456.789.012-34',
    tipo_parceria: 'Benfeitora Pessoa Física',
    responsavel: 'Heloísa Drummond',
    cargo_responsavel: 'Advogada e Apoiadora Comunitária',
    telefone: '(31) 98877-1122',
    email: 'heloisa.drummond@gmail.com',
    projeto: 'Projeto Afeto',
    status: 'Ativo',
    favorito: false,
    contribuicao: 'Doações mensais para o fundo de acolhimento de mães chefes de família.',
    created_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  }
];

